apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finvista-chroma-pvc
  labels:
    app: finvista-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finvista-uploads-pvc
  labels:
    app: finvista-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
