apiVersion: v1
kind: Service
metadata:
  name: finvista-rag-service
  labels:
    app: finvista-rag
spec:
  type: LoadBalancer
  selector:
    app: finvista-rag
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
      name: http
